env:
  -SOURCE_BRANCH="master"
  -DEPLOY_BRANCH="Deploy"
  -SOURCE_DIR="dist"
  -DEPLOY_DIR="public"
  -DEPLOY_REPO="https://github.com/MarcinJarecki/React-js-Sticky-Notes.git"
  -DEPLOY_REPO_NAME="React-js-Sticky-Notes"
language: node_js
node_js:
- '6.1'
install:
- npm install
before_install:
- openssl aes-256-cbc -K $encrypted_00be96f15679_key -iv $encrypted_00be96f15679_iv -in github_deploy_key.enc -out github_deploy_key -d
script:
- npm test
- npm run build
after_success:
- chmod 600 github_deploy_key
- eval "$(ssh-agent -s)"
- ssh-add github_deploy_key
- git config --global user.name $GH_USER_NAME
- git config --global user.email $GH_USER_EMAIL
- REPO=$(git config remote.origin.url)
- REV=$(git rev-parse HEAD)
- git clone --depth=50 --branch=deploy $DEPLOY_REPO
- rsync -rt --delete --exclude=".git" --exclude=".travis.yml" $SOURCE_DIR/ $DEPLOY_REPO_NAME/$DEPLOY_DIR/
- cd $DEPLOY_REPO_NAME/$DEPLOY_DIR
- ls
- git add -A . 
- git commit --allow-empty -m "Travis build  $TRAVIS_BUILD_ID Buil from commit $REV"
- git push -fq origin deploy
notifications:
  email:
    on_success: never
