language: node_js
node_js: 
- '6.1'
install:
- npm install
before_install:
- openssl aes-256-cbc -K $encrypted_00be96f15679_key -iv $encrypted_00be96f15679_iv -in github_deploy_key.enc -out github_deploy_key -d
script:
- npm test
- npm run build
notifications:
  email:
    on_success: never
