env:
  -SOURCE_BRANCH="master"
  -TARGET_BRANCH="Deploy"
  -SOURCE_DIR="dist"
  -TARGET_DIR="public"
language: node_js
node_js:
- '6.1'
install:
- npm install
before_install:
- openssl aes-256-cbc -K $encrypted_00be96f15679_key -iv $encrypted_00be96f15679_iv -in github_deploy_key.enc -out github_deploy_key -d
script:
- npm test
- npm run build
after_success:
- chmod 600 github_deploy_key
- eval "$(ssh-agent -s)"
- ssh-add github_deploy_key
- git config user.name $GH_USER_NAME
- git config user.email $GH_USER_EMAIL
- REPO=$(git config remote.origin.url)
- REV=$(git rev-parse HEAD)
- git clone --branch ${TARGET_BRANCH} ${REPO} ${TARGET_DIR}
- ls
- rsync -rt --delete --exclude=".git" --exclude=".travis.yml" $SOURCE_DIR/ $TARGET_DIR/
- cd ..
- ls
- git checkout $TARGET_BRANCH
- git checkout master -- $TARGET_DIR
- ls
- git add $TARGET_DIR
- git commit --allow-empty -m "Travis build  $TRAVIS_BUILD_ID Buil from commit $REV"
- git push -fq $REPO $TARGET_BRANCH
notifications:
  email:
    on_success: never
